version: '2'
services:
    influxdb:
        image: influxdb:1.6.3-alpine
        container_name: influxdb
        volumes:
            - "./conf/influxdb:/data"        
        environment:
            - PRE_CREATE_DB="sensordata"
    mosquitto:
        image: pascaldevink/rpi-mosquitto
        container_name: mosquitto
        ports:
            - "1883:1883"
        volumes:
            - "./conf/mosquitto/config:/mqtt/config:ro"
            - "./conf/mosquitto/log:/mqtt/log"
            - "./conf/mosquitto/data/:/mqtt/data/"
    grafana:
        image: grafana/grafana
        container_name: grafana
        depends_on:
            - influxdb
        ports:
            - "3000:3000"
        volumes:
            - "./conf/grafana/config:/etc/grafana"
            - "./conf/grafana/storage:/data"
    mqtt2influxdb:
        image: sglahn/mqtt2influxdb
        container_name: mqtt2influxdb
        depends_on:
            - influxdb
            - mosquitto
        volumes:
            - "./conf/mqtt2influxdb/:/config"
    ota-server:
        image: sglahn/ota-server
        container_name: ota-server
        volumes: 
           - "./conf/ota-server/firmware/:/firmware"
        ports:
           - 8000:8000

