version: '2'
services:
    influxdb:
        image: influxdb:1.6.3-alpine
        ports:
            - "8086:8086"
        volumes:
            - "./conf/influxdb:/data"        
        environment:
            - PRE_CREATE_DB="sensordata"
